/**
 * Generic renderer for an AI Career Hub response that only guarantees a
 * `result` free-text string (career coach / resume rewrite / mock
 * interview all fall back to this shape whenever the shared AI provider
 * answered directly, since only the local rule-based fallback path adds
 * a structured `details` object). Reused across those tools instead of
 * duplicating this card three times.
 */
import CopyButton from "./CopyButton";

export default function AIResultCard({ title, message, fallback, resultText }) {
  return (
    <div className="card" style={{ padding: "var(--space-lg)", marginTop: "var(--space-lg)" }}>
      <div style={{ display: "flex", alignItems: "center", gap: "var(--space-sm)", flexWrap: "wrap", justifyContent: "space-between" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "var(--space-sm)", flexWrap: "wrap" }}>
          {title && <span className="badge badge-accent">{title}</span>}
          {fallback && <span className="badge badge-neutral">Generated by built-in fallback</span>}
        </div>
        <CopyButton text={resultText} />
      </div>
      {fallback && message && (
        <p style={{ marginTop: "var(--space-sm)", fontSize: "0.85em", color: "var(--color-text-muted, #666)" }}>{message}</p>
      )}
      <pre
        style={{
          marginTop: "var(--space-md)",
          whiteSpace: "pre-wrap",
          wordBreak: "break-word",
          fontFamily: "var(--font-body)",
          fontSize: "0.95em",
          color: "var(--color-text)",
        }}
      >
        {resultText}
      </pre>
    </div>
  );
}
